version: '3'
services:
  zookeeper:
    container_name: zookeeper-container
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
      #ZOOKEEPER_CLIENT_PORT: 2181
      #ZOOKEEPER_TICK_TIME: 2000

    volumes:
      # sudo mkdir /var/lib/zookeeper &&  sudo chown -R 1000:1000 /var/lib/zookeeper
      - /var/lib/zookeeper:/var/lib/zookeeper

  kafka:
    container_name: kafka-container
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER:  "yes"
    volumes:
      # sudo mkdir /var/lib/kafka &&  sudo chown -R 1000:1000 /var/lib/kafka
      - /var/lib/kafka:/var/lib/kafka
    depends_on:
      - zookeeper    




  nifi-seed:
    container_name: nifi-seed-container
    image: torklu/my_nifi
    ports:
      - "8080-8082:8080-8082"
    depends_on:
      - zookeeper
      - kafka

    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      # sudo mkdir /var/lib/nifi && sudo chown -R 1000:1000 /var/lib/nifi
      - /var/lib/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - /var/lib/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - /var/lib/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - /var/lib/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - /var/lib/nifi/state:/opt/nifi/nifi-current/state
      - /var/lib/nifi/logs:/opt/nifi/nifi-current/logs

  nifi-nodes:
    container_name: nifi-node-container
    image: torklu/my_nifi
    depends_on:
      - nifi-seed
